# Generated by Django 4.2.15 on 2024-08-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=' ', max_length=128),
            preserve_default=False,
        ),
    ]
